# Site Info
title: 제목
tagline: '태그라인 넣을거'
description: '설명'
baseurl: ""
url: http://jo631.github.io
logo: '/public/logo.png' #로고 바꾸기

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: CastleJo
  description: 설명
  gravatar: 2cab55d41d9385e34db30faa9d180db1 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/lizhihao ##xx
    github:    https://github.com/jo631
    # facebook:  <hide>
    twitter:   https://twitter.com/Li_Zhihao ##xx
    weibo:     http://weibo.com/41173780 ##xx
    email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM= ##x

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/categories/'
    - { TIL (Today I Learned): '/blog/categories/#TiL' }
    - { 잡다한 이야기: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://jo631.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

main_jpg:
  image: /public/img/moon.jpg
  caption: 설명

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

